import './bootstrap';
import './sla-countdown';
import './invoice-copy';
import './permission-pill';
import './credential-mask';
import './packing-check';
import './confirm-modal';
import './busy-overlay';
import './channel-order-fetch';
import './automation-run';
import './thumb-fallback';
import './plot-readout';
import './list-filters';
import './nav-progress';
import './order-selection';
import './order-thumb-preview';
import './field-a11y';
import './hint-place';
import './desk-tools';
import './legacy-flash';
import './pages/shopee-orders';
import './pages/lazada-orders';
import './pages/tiktok-orders';
import './pages/shopify-orders';
import './pages/ventacart-orders';
import './pages/pedallion';
import './pages/pedallion-listings';
import './pages/order-detail';
import './pages/product-form';
import './pages/shopee-listings';
import './pages/lazada-listings';
import './pages/tiktok-listings';
import './pages/ventacart-listings';
import './pages/woocommerce-listings';
import './pages/channel-settings';
import './pages/channel-setup';
import './pages/store-settings';
import './pages/group-form';
import './pages/description-template';
import './pages/description-preview';
import './pages/image-library';
import './pages/product-video';
import './pages/watermark-form';
import './pages/listing-images';
import './pages/catalog-change';
import './pages/listing-status-menu';
import './pages/category-tree-pick';
import './pages/listing-video';
import './pages/row-picked';
import './pages/listing-group-band';
import './pages/listing-strip';
import './pages/unsaved-guard';
import './pages/gap-jump';
import './pages/required-group';
import './pages/group-products';
import './pages/channel-listing-form';
import './pages/channel-import';
import './pages/channel-add';
import './pages/channel-add-panel';
import './pages/purchasing';
import './pages/product-vendors';
import './pages/warehousing';
import './pages/reports';
import './pages/reviews';
import './pages/settings';
import './pages/ai-tools';
import './pages/order-form';
import './pages/push-review';

import { initNavGroups } from './nav-groups';
import ventasyncPalette from './palette';
import pettyCash from './pages/petty-cash';
import credentialField from './credential-field';

import Alpine from 'alpinejs';

initNavGroups();

window.Alpine = Alpine;
Alpine.data('ventasyncPalette', ventasyncPalette);
Alpine.data('pettyCash', pettyCash);
Alpine.data('credentialField', credentialField);
Alpine.start();

requestAnimationFrame(() => {
    requestAnimationFrame(() => document.querySelector('.bl-app')?.classList.add('is-ready'));
});
